### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Evolvee** [XiconQoo/TotemRadius-TBC#1]
This would be huge if it was for enemy players as well.. to see where you can fear someone and where not.

Also for rogues, it would be nice to implement this into stealth, showing where you can be seen by other rogues. Later expansions have this by adding lightweight white circle around your char that moves with you.

Also, this would be huge for mages, priest and wlocks, if it was indicating maxrange of blizzard, mass dispel etc. on mouseover when you select the spell, currently you have to find the max range the hard way.

**Comment by XiconQoo** [comment]
@Evolvee For enemy totems this is not possible unfortunately, because you can't get an enemies x,y coords. You can get coords only for yourself and I believe party/raidmembers.

For mass-dispel/blizzard, I think it's hard as well, since there is no event, before you cast it. So it is hard to trigger.

For rogues stealth (only your own): Possible, yes. You could make a scene in AVR and toggle it with stealth active or not. For that you basically need AVR only, no TotemRadius needed.
